<?php
/**
 * ExportManager class for WikiPress plugin.
 * @package WikiPress
 * @subpackage Admin\Manager\Tools
 * @since 1.0.0
 */
namespace TrilBDev\WikiPress\Admin\Manager\Tools;

use TrilBDev\WikiPress\Admin\Manager\Manager;
use TrilBDev\WikiPress\Includes\Functions\Helpers\FormFieldHelper;
use TrilBDev\WikiPress\Includes\Functions\Helpers\UrlHelper;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

final class ImportManager extends Manager {
    /**
     * Constructor for the ImportManager class.
     *
     * @since 1.0.0
     */
    public function __construct() {
    }

    /**
     * Render the JSON import form below the tools settings form.
     *
     * @return void
     */
    public function render(): void {
        ?>
        <form method="post" action="<?php echo esc_url( UrlHelper::admin_action( 'wikipress_import' ) ); ?>" enctype="multipart/form-data" class="card wikipress-import-form shadow-sm mt-4">
            <?php echo FormFieldHelper::input( 'action', 'wikipress_import', [ 'type' => 'hidden' ] ); ?>
            <?php wp_nonce_field( 'wikipress_import' ); ?>
            <div class="card-body"><?php echo FormFieldHelper::label( 'wikipress-import-file', __( 'Import WikiPress JSON', 'wikipress' ), [ 'description' => __( 'Select a JSON export generated by WikiPress.', 'wikipress' ), 'tooltip' => __( 'Importing replaces matching WikiPress data with the contents of the file.', 'wikipress' ), 'tooltip_icon' => 'fa-file-import' ] ); ?><?php echo FormFieldHelper::input( 'wikipress_import_file', '', [ 'id' => 'wikipress-import-file', 'type' => 'file', 'class' => 'mb-3', 'accept' => 'application/json,.json', 'required' => true ] ); ?><?php echo FormFieldHelper::button( __( 'Import JSON', 'wikipress' ), [ 'type' => 'submit', 'class' => 'btn-primary' ] ); ?></div>
        </form>
        <?php
    }
}