<?php

namespace TrilBDev\WikiPress\Admin\Manager\Settings;

use TrilBDev\WikiPress\Includes\Functions\Helpers\FormFieldHelper;
use TrilBDev\WikiPress\Includes\Functions\Helpers\UrlHelper;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class SettingsTools {
	/**
	 * Render tools settings fields and import controls.
	 *
	 * @param array<string, mixed> $values Current settings.
	 * @return void
	 */
	public function render( array $values ): void {
		$debug_id = 'wikipress-debug-logging';
		$debug_field = [ 'description' => __( 'Write diagnostic information to the WordPress debug log.', 'wikipress' ), 'tooltip' => __( 'Enable this only while investigating a problem, because logs can grow over time.', 'wikipress' ), 'tooltip_type' => 'info' ];
		echo '<tr><th scope="row">' . FormFieldHelper::label( $debug_id, __( 'Debug logging', 'wikipress' ), $debug_field ) . '</th><td>' . FormFieldHelper::checkbox( 'wikipress_tools[debug_logging]', '1', __( 'Enable WikiPress debug logging', 'wikipress' ), [ 'id' => $debug_id, 'checked' => ! empty( $values['debug_logging'] ) ] ) . '</td></tr>';
		$console_id = 'wikipress-console-logging';
		$console_field = [ 'description' => __( 'Write diagnostic information to the browser console.', 'wikipress' ), 'tooltip' => __( 'Use this during frontend troubleshooting and disable it afterward.', 'wikipress' ) ];
		echo '<tr><th scope="row">' . FormFieldHelper::label( $console_id, __( 'Console logging', 'wikipress' ), $console_field ) . '</th><td>' . FormFieldHelper::checkbox( 'wikipress_tools[console_logging]', '1', __( 'Enable browser console logging', 'wikipress' ), [ 'id' => $console_id, 'checked' => ! empty( $values['console_logging'] ) ] ) . '</td></tr>';
		echo '<tr><th scope="row">' . FormFieldHelper::label( 'wikipress-export', esc_html__( 'Import and export', 'wikipress' ), [ 'description' => __( 'Export or import WikiPress content and settings as JSON.', 'wikipress' ), 'tooltip' => __( 'Exports are protected with a WordPress nonce.', 'wikipress' ) ] ) . '</th><td>' . FormFieldHelper::button( esc_html__( 'Export WikiPress JSON', 'wikipress' ), [ 'href' => UrlHelper::admin_action_nonce( 'wikipress_export', 'wikipress_export' ), 'class' => 'btn-outline-primary' ] ) . '</td></tr>';
		echo '<tr><th scope="row">' . FormFieldHelper::label( 'wikipress-database-manager', esc_html__( 'Database manager', 'wikipress' ), [ 'description' => __( 'The settings table is managed automatically during plugin activation.', 'wikipress' ), 'tooltip' => __( 'Manual database changes are not required for normal WikiPress operation.', 'wikipress' ) ] ) . '</th><td>' . esc_html__( 'Managed automatically', 'wikipress' ) . '</td></tr>';
	}

	/**
	 * Render the JSON import form.
	 *
	 * @return void
	 */
	public function render_import_form(): void {
		?>
		<form method="post" action="<?php echo esc_url( UrlHelper::admin_action( 'wikipress_import' ) ); ?>" enctype="multipart/form-data" class="card wikipress-import-form shadow-sm mt-4">
			<?php echo FormFieldHelper::input( 'action', 'wikipress_import', [ 'type' => 'hidden' ] ); ?>
			<?php wp_nonce_field( 'wikipress_import' ); ?>
			<div class="card-body"><?php echo FormFieldHelper::label( 'wikipress-import-file', __( 'Import WikiPress JSON', 'wikipress' ), [ 'description' => __( 'Select a JSON export generated by WikiPress.', 'wikipress' ), 'tooltip' => __( 'Importing replaces matching WikiPress data with the contents of the file.', 'wikipress' ), 'tooltip_icon' => 'fa-file-import' ] ); ?><?php echo FormFieldHelper::input( 'wikipress_import_file', '', [ 'id' => 'wikipress-import-file', 'type' => 'file', 'class' => 'mb-3', 'accept' => 'application/json,.json', 'required' => true ] ); ?><?php echo FormFieldHelper::button( __( 'Import JSON', 'wikipress' ), [ 'type' => 'submit', 'class' => 'btn-primary' ] ); ?></div>
		</form>
		<?php
	}
}
